### ISSUE TITLE
Export CIFS Clients

### ISSUE THREAD

**Issue by bamorris** [nasuni-labs/nasuni-nmcapi-powershell-utilities#5]
Hello,
    The ExportCifsClientsToCSV script is only pulling the first fifty filers for me.  Is there a way to adjust the amount of filers to get all currently connected clients?

**Comment by cdillahunty-nasuni** [comment]
The latest version of the script (refactored for NMC 22.2) shouldn't have this limitation. https://github.com/nasuni-labs/nasuni-nmcapi-powershell-utilities/blob/main/Access_Points/Shares/ExportCifsClientsToCSV.ps1
