### ISSUE TITLE
400 error with CreateShareFromCSV

### ISSUE THREAD

**Issue by sc-tbailey1** [nasuni-labs/nasuni-nmcapi-powershell-utilities#6]
Has anyone gotten this to work?  On the line defining $jsonBody there was "-Depth 3" parameter set for ConvertFrom-Json, but this command doesn't have that parameter so I've removed it.  At the line where the share gets created with the Invoke-RestMethod command I'm receiving a 400 Bad Request error which looks to mean the body is incorrect.  Here's what the $jsonBody variable looks like with my entries in CSV file.  The path does in-fact exist.

    {
    "name": "share-test",
    "path": "\\shares\\share-test",
    "comment": "share-test",
    "readonly": ,
    "browseable": true,
    "hosts_allow": "",
    "hide_unreadable": false,
    "enable_previous_vers": ,
    "case_sensitive": ,
    "enable_snapshot_dirs": ,
    "homedir_support": ,
    "mobile": ,
    "browser_access": ,
    "browser_access_settings": {
        "shared_links_enabled": false,
        "link_force_password": true,
        "link_allow_rw": false,
        "external_share_url": "",
        "link_expire_limit": 30,
        "link_auth": {
            "authall": true,
            "allow_groups_ro": [],
            "allow_groups_rw": [],
            "deny_groups": [],
            "allow_users_ro": [],
            "allow_users_rw": [],
            "deny_users": []
        }
    },
    "aio_enabled": true,
    "veto_files": ".DS_Store",
    "fruit_enabled": true,
    "smb_encrypt": "",
    "auth": {
        "authall": true,
        "rw_groups": [],
        "ro_groups": [],
        "deny_groups": [],
        "rw_users": [],
        "ro_users": [],
        "deny_users": []
    }}

**Comment by sc-tbailey1** [comment]
Issue is with some of the options ("case_sensitive", for example) it requires some kind of setting in the CSV (TRUE or FALSE) else a blank will be put into the JSON file and this was the issue.

**Comment by cdillahunty-nasuni** [comment]
We need to work on the documentation for the CreateShareFromCSV script, including an updated CSV that you can use as the input. The script is designed to process output from the https://github.com/nasuni-labs/nasuni-nmcapi-powershell-utilities/blob/main/Access_Points/Shares/ExportSharesToCSV.ps1 script. If you'd like to see the format you need for import, you can run the export and view the results.
